[package]
name = "overload"
version = "0.1.1"
authors = ["Daniel Salvadori <danaugrs@gmail.com>"]
description = "Provides a macro to simplify operator overloading."
license = "MIT"
keywords = ["operator", "overloading", "macro", "op"]
categories = ["rust-patterns"]
repository = "https://github.com/danaugrs/overload"
edition = "2018"
